spring:
  application:
    name: SmartContactManager
  #DB configuration mysql

  datasource:
    url: jdbc:mysql://localhost:3306/scm2O
    username: root
    password: root@12345
    driver-class-name: com.mysql.cj.jdbc.Driver

    #jpa configuration
  jpa:
    show-sql: true                            # Show SQL queries in the console
    hibernate:
      ddl-auto: update                        # Manage schema creation/update. Options: create, create-drop, update, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Dialect for MySQL 8  
   
  

  # spring security configruration
  security:
    user:
      name: mohit
      password: mohit123
# google O Auth
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 533497835908-nqu222i038vjfltcjlot3n00s1eoeuno.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
        # provider:
        #   google:
        #     authorization-uri: https://accounts.google.com/o/oauth2/auth
        #     token-uri: https://oauth2.googleapis.com/token
        #     user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
        #     user-name-attribute: sub


#for git O auth checck applicaiton.perties



logging:
  level:
    org.springframework.security: WARN

# logging:
#   level:
#     root: DEBUG  # Increases logging for entire Spring Boot application
#     org.springframework: DEBUG  # Specifically for Spring-related logs
#     org.springframework.security: DEBUG  # Security-specific logs

